// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N.EntityFrameworkCore.Extensions.Test.Data;

#nullable disable

namespace N.EntityFrameworkCore.Extensions.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250509021251_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
