using System;
using System.Collections.Generic;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using N.EntityFrameworkCore.Extensions.Common;
using N.EntityFrameworkCore.Extensions.Sql;
using N.EntityFrameworkCore.Extensions.Util;

namespace N.EntityFrameworkCore.Extensions;

internal sealed partial class BulkOperation<T> : IDisposable
{
    internal DbConnection Connection => DbTransactionContext.Connection;
    internal DbContext Context { get; }
    internal bool StagingTableCreated { get; set; }
    internal string StagingTableName { get; }
    internal string[] PrimaryKeyColumnNames { get; }
    internal BulkOptions Options { get; }
    internal Expression<Func<T, object>> InputColumns { get; }
    internal Expression<Func<T, object>> IgnoreColumns { get; }
    internal DbTransactionContext DbTransactionContext { get; }
    internal Type EntityType => typeof(T);
    internal DbTransaction Transaction => DbTransactionContext.CurrentTransaction;
    internal TableMapping TableMapping { get; }
    internal IEnumerable<string> SchemaQualifiedTableNames => TableMapping.GetSchemaQualifiedTableNames();


    public BulkOperation(DbContext dbContext, BulkOptions options, Expression<Func<T, object>> inputColumns = null, Expression<Func<T, object>> ignoreColumns = null)
    {
        Context = dbContext;
        Options = options;
        InputColumns = inputColumns;
        IgnoreColumns = ignoreColumns;

        DbTransactionContext = new DbTransactionContext(dbContext, options.CommandTimeout);
        TableMapping = dbContext.GetTableMapping(typeof(T), options.EntityType);
        StagingTableName = CommonUtil.GetStagingTableName(TableMapping, options.UsePermanentTable, Connection);
        PrimaryKeyColumnNames = TableMapping.GetPrimaryKeyColumns().ToArray();
    }
    public void Dispose()
    {
        if (StagingTableCreated)
        {
            Context.Database.DropTable(StagingTableName, true);
        }
    }
    internal bool ShouldKeepIdentityForMerge()
    {
        // MySQL does not support keeping identity values for merge in the same way as PostgreSQL
        return false;
    }
    internal bool ShouldPreallocateIdentityValues(bool autoMapOutput, bool keepIdentity, IEnumerable<T> entities)
    {
        // MySQL does not support preallocating identity values
        return false;
    }
    internal void PreallocateIdentityValues(IEnumerable<T> entities)
    {
        // No-op for MySQL
    }
    internal BulkInsertResult<T> BulkInsertStagingData(IEnumerable<T> entities, bool keepIdentity = true, bool useInternalId = false)
    {
        IEnumerable<string> columnsToInsert = GetColumnNames(keepIdentity);
        string internalIdColumn = useInternalId ? Common.Constants.InternalId_ColumnName : null;
        Context.Database.CloneTable(SchemaQualifiedTableNames, StagingTableName, TableMapping.GetQualifiedColumnNames(columnsToInsert), internalIdColumn);
        StagingTableCreated = true;
        return DbContextExtensions.BulkInsert(entities, Options, TableMapping, Connection, Transaction, StagingTableName, columnsToInsert, useInternalId);
    }
    internal BulkMergeResult<T> ExecuteMerge(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update = false, bool delete = false, bool preallocatedIds = false)
    {
        return ExecuteMergeMySql(entityMap, mergeOnCondition, autoMapOutput, keepIdentity, insertIfNotExists, update, delete, preallocatedIds);
    }

    private IEnumerable<string> GetMergeOutputColumns(IEnumerable<string> autoGeneratedColumns, bool delete = false)
    {
        List<string> columnsToOutput = ["$action", $"[s].[{Constants.InternalId_ColumnName}]"];
        columnsToOutput.AddRange(autoGeneratedColumns.Select(o => $"[inserted].[{o}]"));
        return columnsToOutput;
    }
    private object[] GetMergeOutputValues(IEnumerable<string> columns, object[] values, IEnumerable<IProperty> properties)
    {
        var columnList = columns.ToList();
        var valuesIndex = properties.Select(o => columnList.IndexOf($"[inserted].[{o.GetColumnName()}]"));
        return valuesIndex.Select(i => values[i]).ToArray();
    }
    internal int ExecuteUpdate(IEnumerable<T> entities, Expression<Func<T, T, bool>> updateOnCondition)
    {
        return ExecuteUpdateMySql(updateOnCondition);
    }
    private BulkMergeResult<T> ExecuteMergeMySql(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update, bool delete, bool preallocatedIds = false)
    {
        Dictionary<IEntityType, int> rowsInserted = [];
        Dictionary<IEntityType, int> rowsUpdated = [];
        Dictionary<IEntityType, int> rowsDeleted = [];
        List<BulkMergeOutputRow<T>> outputRows = [];

        foreach (var entityType in TableMapping.EntityTypes)
        {
            var targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            var columnsToInsert = GetColumnNames(entityType, keepIdentity).ToList();
            var columnsToUpdate = update ? GetColumnNames(entityType).ToList() : [];
            var autoGeneratedColumns = autoMapOutput ? TableMapping.GetAutoGeneratedColumns(entityType).ToList() : [];
            var allProperties = autoMapOutput
                ? TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAdd).Concat(TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAddOrUpdate)).ToList()
                : [];

            string matchJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, mergeOnCondition, PrimaryKeyColumnNames, "s", "t");
            string pkJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, null, PrimaryKeyColumnNames, "s", "t");
            string joinCondition = insertIfNotExists ? matchJoinCondition : "1=2";

            HashSet<int> matchedIds = autoMapOutput && update
                ? GetMatchedInternalIds(targetTableName, matchJoinCondition)
                : [];

            rowsUpdated[entityType] = 0;
            if (columnsToUpdate.Count > 0)
            {
                // MySQL UPDATE with JOIN syntax
                string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"t.{Context.DelimitIdentifier(c)}=s.{Context.DelimitIdentifier(c)}"));
                string updateSql = $"UPDATE {StagingTableName} AS s INNER JOIN {targetTableName} AS t ON {joinCondition} SET {updateSetExpression}";
                rowsUpdated[entityType] = Context.Database.ExecuteSqlInternal(updateSql, Options.CommandTimeout);
            }

            string insertColumnsSql = string.Join(",", columnsToInsert.Select(Context.DelimitIdentifier));
            string sourceColumnsSql = string.Join(",", columnsToInsert.Select(c => Context.DelimitMemberAccess("s", c)));
            string insertSql = $"INSERT INTO {targetTableName} ({insertColumnsSql}) SELECT {sourceColumnsSql} FROM {StagingTableName} AS s WHERE NOT EXISTS (SELECT 1 FROM {targetTableName} AS t WHERE {joinCondition})";
            rowsInserted[entityType] = Context.Database.ExecuteSqlInternal(insertSql, Options.CommandTimeout);
            if (keepIdentity && rowsInserted[entityType] > 0)
                SyncMySqlAutoIncrement(entityType);

            rowsDeleted[entityType] = 0;
            if (TableMapping.EntityType == entityType && delete)
            {
                string deleteJoinCondition = (preallocatedIds && mergeOnCondition != null) ? matchJoinCondition : pkJoinCondition;
                // MySQL multi-table DELETE syntax: DELETE alias FROM table AS alias WHERE ...
                string deleteSql = $"DELETE t FROM {targetTableName} AS t WHERE NOT EXISTS (SELECT 1 FROM {StagingTableName} AS s WHERE {deleteJoinCondition})";
                rowsDeleted[entityType] = Context.Database.ExecuteSqlInternal(deleteSql, Options.CommandTimeout);
                for (int i = 0; i < rowsDeleted[entityType]; i++)
                    outputRows.Add(new BulkMergeOutputRow<T>(SqlMergeAction.Delete));
            }

            if (autoMapOutput)
            {
                string outputColumnsSql = autoGeneratedColumns.Any()
                    ? "," + string.Join(",", autoGeneratedColumns.Select(c => Context.DelimitMemberAccess("t", c)))
                    : string.Empty;
                var outputQuery = $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)}{outputColumnsSql} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {matchJoinCondition}";
                var bulkQueryResult = Context.BulkQuery(outputQuery, Options);
                var autoGeneratedColumnList = autoGeneratedColumns.ToList();
                foreach (var result in bulkQueryResult.Results)
                {
                    int entityId = Convert.ToInt32(result[0]);
                    bool wasMatched = matchedIds.Contains(entityId);
                    string action = wasMatched ? SqlMergeAction.Update : SqlMergeAction.Insert;
                    outputRows.Add(new BulkMergeOutputRow<T>(action));

                    if (entityMap.TryGetValue(entityId, out var entity) && allProperties.Count > 0)
                    {
                        object[] entityValues = allProperties.Select(p => result[1 + autoGeneratedColumnList.IndexOf(p.GetColumnName())]).ToArray();
                        Context.SetStoreGeneratedValues(entity, allProperties, entityValues);
                    }
                }
            }
        }

        return new BulkMergeResult<T>
        {
            Output = outputRows,
            RowsAffected = rowsInserted.Values.LastOrDefault() + rowsUpdated.Values.LastOrDefault() + rowsDeleted.Values.LastOrDefault(),
            RowsDeleted = rowsDeleted.Values.LastOrDefault(),
            RowsInserted = rowsInserted.Values.LastOrDefault(),
            RowsUpdated = rowsUpdated.Values.LastOrDefault()
        };
    }
    private int ExecuteUpdateMySql(Expression<Func<T, T, bool>> updateOnCondition)
    {
        int rowsUpdated = 0;
        foreach (var entityType in TableMapping.EntityTypes)
        {
            IEnumerable<string> columnsToUpdate = GetColumnNames(entityType);
            string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"t.{Context.DelimitIdentifier(c)}=s.{Context.DelimitIdentifier(c)}"));
            string targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            // MySQL UPDATE with JOIN syntax
            string updateSql = $"UPDATE {StagingTableName} AS s INNER JOIN {targetTableName} AS t ON {CommonUtil<T>.GetJoinConditionSql(Context, updateOnCondition, PrimaryKeyColumnNames, "s", "t")} SET {updateSetExpression}";
            rowsUpdated = Context.Database.ExecuteSqlInternal(updateSql, Options.CommandTimeout);
        }
        return rowsUpdated;
    }
    private HashSet<int> GetMatchedInternalIds(string targetTableName, string joinCondition)
    {
        var results = Context.BulkQuery(
            $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {joinCondition}",
            Options);
        return results.Results.Select(r => Convert.ToInt32(r[0])).ToHashSet();
    }
    private IProperty GetGeneratedPrimaryKeyProperty()
    {
        return TableMapping.EntityType.GetProperties().SingleOrDefault(o => o.IsPrimaryKey() && o.ValueGenerated != ValueGenerated.Never);
    }
    private void SyncMySqlAutoIncrement(IEntityType entityType)
    {
        var tableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
        // Reset AUTO_INCREMENT to resync after bulk insert with explicit IDs
        Context.Database.ExecuteSqlInternal($"ALTER TABLE {tableName} AUTO_INCREMENT = 1", Options.CommandTimeout);
    }
    internal void ValidateBulkMerge(Expression<Func<T, T, bool>> mergeOnCondition)
    {
        if (PrimaryKeyColumnNames.Length == 0 && mergeOnCondition == null)
            throw new InvalidDataException("BulkMerge requires that the entity have a primary key or that Options.MergeOnCondition be set");
    }
    internal void ValidateBulkUpdate(Expression<Func<T, T, bool>> updateOnCondition)
    {
        if (PrimaryKeyColumnNames.Length == 0 && updateOnCondition == null)
            throw new InvalidDataException("BulkUpdate requires that the entity have a primary key or the Options.UpdateOnCondition must be set.");

    }
    internal IEnumerable<string> GetColumnNames(bool includePrimaryKeys = false)
    {
        return GetColumnNames(null, includePrimaryKeys);
    }
    internal IEnumerable<string> GetColumnNames(IEntityType entityType, bool includePrimaryKeys = false)
    {
        return CommonUtil.FilterColumns(TableMapping.GetColumnNames(entityType, includePrimaryKeys), PrimaryKeyColumnNames, InputColumns, IgnoreColumns);
    }
}
