using System;
using System.Collections.Generic;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using N.EntityFrameworkCore.Extensions.Common;
using N.EntityFrameworkCore.Extensions.Sql;
using N.EntityFrameworkCore.Extensions.Util;

namespace N.EntityFrameworkCore.Extensions;

internal sealed partial class BulkOperation<T> : IDisposable
{
    internal DbConnection Connection => DbTransactionContext.Connection;
    internal DbContext Context { get; }
    internal bool StagingTableCreated { get; set; }
    internal string StagingTableName { get; }
    internal string[] PrimaryKeyColumnNames { get; }
    internal BulkOptions Options { get; }
    internal Expression<Func<T, object>> InputColumns { get; }
    internal Expression<Func<T, object>> IgnoreColumns { get; }
    internal DbTransactionContext DbTransactionContext { get; }
    internal Type EntityType => typeof(T);
    internal DbTransaction Transaction => DbTransactionContext.CurrentTransaction;
    internal TableMapping TableMapping { get; }
    internal IEnumerable<string> SchemaQualifiedTableNames => TableMapping.GetSchemaQualifiedTableNames();


    public BulkOperation(DbContext dbContext, BulkOptions options, Expression<Func<T, object>> inputColumns = null, Expression<Func<T, object>> ignoreColumns = null)
    {
        Context = dbContext;
        Options = options;
        InputColumns = inputColumns;
        IgnoreColumns = ignoreColumns;

        DbTransactionContext = new DbTransactionContext(dbContext, options.CommandTimeout);
        TableMapping = dbContext.GetTableMapping(typeof(T), options.EntityType);
        StagingTableName = CommonUtil.GetStagingTableName(TableMapping, options.UsePermanentTable, Connection);
        PrimaryKeyColumnNames = TableMapping.GetPrimaryKeyColumns().ToArray();
    }
    public void Dispose()
    {
        if (StagingTableCreated)
            Context.Database.DropTable(StagingTableName, true);
        DbTransactionContext.Dispose();
    }
    internal bool ShouldKeepIdentityForMerge() => false;
    internal bool ShouldPreallocateIdentityValues(bool autoMapOutput, bool keepIdentity, IEnumerable<T> entities) => false;
    internal void PreallocateIdentityValues(IEnumerable<T> entities) { }
    internal BulkInsertResult<T> BulkInsertStagingData(IEnumerable<T> entities, bool keepIdentity = true, bool useInternalId = false)
    {
        IEnumerable<string> columnsToInsert = GetColumnNames(keepIdentity);
        string internalIdColumn = useInternalId ? Common.Constants.InternalId_ColumnName : null;
        Context.Database.CloneTable(SchemaQualifiedTableNames, StagingTableName, TableMapping.GetQualifiedColumnNames(columnsToInsert), internalIdColumn);
        StagingTableCreated = true;
        return DbContextExtensions.BulkInsert(entities, Options, TableMapping, Connection, Transaction, StagingTableName, columnsToInsert, useInternalId);
    }
    internal BulkMergeResult<T> ExecuteMerge(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update = false, bool delete = false, bool preallocatedIds = false)
    {
        if (Context.Database.IsSqliteProvider())
            return ExecuteMergeSqlite(entityMap, mergeOnCondition, autoMapOutput, keepIdentity, insertIfNotExists, update, delete, preallocatedIds);

        Dictionary<IEntityType, int> rowsInserted = [];
        Dictionary<IEntityType, int> rowsUpdated = [];
        Dictionary<IEntityType, int> rowsDeleted = [];
        Dictionary<IEntityType, int> rowsAffected = [];
        List<BulkMergeOutputRow<T>> outputRows = [];

        foreach (var entityType in TableMapping.EntityTypes)
        {
            rowsInserted[entityType] = 0;
            rowsUpdated[entityType] = 0;
            rowsDeleted[entityType] = 0;
            rowsAffected[entityType] = 0;

            var columnsToInsert = GetColumnNames(entityType, keepIdentity);
            var columnsToUpdate = update ? GetColumnNames(entityType) : [];
            var autoGeneratedColumns = autoMapOutput ? TableMapping.GetAutoGeneratedColumns(entityType) : [];
            var columnsToOutput = autoMapOutput ? GetMergeOutputColumns(autoGeneratedColumns, delete) : [];
            var deleteEntityType = TableMapping.EntityType == entityType && delete ? delete : false;

            string mergeOnConditionSql = insertIfNotExists ? CommonUtil<T>.GetJoinConditionSql(mergeOnCondition, PrimaryKeyColumnNames, "t", "s") : "1=2";
            bool toggleIdentity = keepIdentity && TableMapping.HasIdentityColumn;
            var mergeStatement = SqlStatement.CreateMerge(StagingTableName, entityType.GetSchemaQualifiedTableName(),
                mergeOnConditionSql, columnsToInsert, columnsToUpdate, columnsToOutput, deleteEntityType, toggleIdentity);

            if (autoMapOutput)
            {
                List<IProperty> allProperties =
                [
                    .. TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAdd).ToArray(),
                        .. TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAddOrUpdate).ToArray()
                ];

                var bulkQueryResult = Context.BulkQuery(mergeStatement.Sql, Options);
                rowsAffected[entityType] = bulkQueryResult.RowsAffected;

                foreach (var result in bulkQueryResult.Results)
                {
                    string action = (string)result[0];
                    outputRows.Add(new BulkMergeOutputRow<T>(action));

                    if (action == SqlMergeAction.Delete)
                    {
                        rowsDeleted[entityType]++;
                    }
                    else
                    {
                        int entityId = (int)result[1];
                        var entity = entityMap[entityId];
                        if (action == SqlMergeAction.Insert)
                        {
                            rowsInserted[entityType]++;
                            if (allProperties.Count != 0)
                            {
                                var entityValues = GetMergeOutputValues(columnsToOutput, result, allProperties);
                                Context.SetStoreGeneratedValues(entity, allProperties, entityValues);
                            }
                        }
                        else if (action == SqlMergeAction.Update)
                        {
                            rowsUpdated[entityType]++;
                            if (allProperties.Count != 0)
                            {
                                var entityValues = GetMergeOutputValues(columnsToOutput, result, allProperties);
                                Context.SetStoreGeneratedValues(entity, allProperties, entityValues);
                            }
                        }
                    }
                }
            }
            else
            {
                rowsAffected[entityType] = Context.Database.ExecuteSqlInternal(mergeStatement.Sql, Options.CommandTimeout);
            }
        }
        return new BulkMergeResult<T>
        {
            Output = outputRows,
            RowsAffected = rowsAffected.Values.LastOrDefault(),
            RowsDeleted = rowsDeleted.Values.LastOrDefault(),
            RowsInserted = rowsInserted.Values.LastOrDefault(),
            RowsUpdated = rowsUpdated.Values.LastOrDefault()
        };
    }

    private IEnumerable<string> GetMergeOutputColumns(IEnumerable<string> autoGeneratedColumns, bool delete = false)
    {
        List<string> columnsToOutput = ["$action", $"[s].[{Constants.InternalId_ColumnName}]"];
        columnsToOutput.AddRange(autoGeneratedColumns.Select(o => $"[inserted].[{o}]"));
        return columnsToOutput;
    }
    private object[] GetMergeOutputValues(IEnumerable<string> columns, object[] values, IEnumerable<IProperty> properties)
    {
        var columnList = columns.ToList();
        var valuesIndex = properties.Select(o => columnList.IndexOf($"[inserted].[{o.GetColumnName()}]"));
        return valuesIndex.Select(i => values[i]).ToArray();
    }
    internal int ExecuteUpdate(IEnumerable<T> entities, Expression<Func<T, T, bool>> updateOnCondition)
    {
        if (Context.Database.IsSqliteProvider())
            return ExecuteUpdateSqlite(updateOnCondition);

        int rowsUpdated = 0;
        foreach (var entityType in TableMapping.EntityTypes)
        {
            IEnumerable<string> columnsToUpdate = CommonUtil.FormatColumns(GetColumnNames(entityType));
            string updateSetExpression = string.Join(",", columnsToUpdate.Select(o => $"t.{o}=s.{o}"));
            string updateSql = $"UPDATE t SET {updateSetExpression} FROM {StagingTableName} AS s JOIN {CommonUtil.FormatTableName(entityType.GetSchemaQualifiedTableName())} AS t ON {CommonUtil<T>.GetJoinConditionSql(updateOnCondition, PrimaryKeyColumnNames, "s", "t")}; SELECT @@RowCount;";
            rowsUpdated = Context.Database.ExecuteSqlInternal(updateSql, Options.CommandTimeout);
        }
        return rowsUpdated;
    }
    private BulkMergeResult<T> ExecuteMergeSqlite(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update, bool delete, bool preallocatedIds = false)
    {
        Dictionary<IEntityType, int> rowsInserted = [];
        Dictionary<IEntityType, int> rowsUpdated = [];
        Dictionary<IEntityType, int> rowsDeleted = [];
        List<BulkMergeOutputRow<T>> outputRows = [];

        foreach (var entityType in TableMapping.EntityTypes)
        {
            var targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            var columnsToInsert = GetColumnNames(entityType, keepIdentity).ToList();
            var columnsToUpdate = update ? GetColumnNames(entityType).ToList() : [];
            var autoGeneratedColumns = autoMapOutput ? TableMapping.GetAutoGeneratedColumns(entityType).ToList() : [];
            var allProperties = autoMapOutput
                ? TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAdd).Concat(TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAddOrUpdate)).ToList()
                : [];

            string matchJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, mergeOnCondition, PrimaryKeyColumnNames, "s", "t");
            string pkJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, null, PrimaryKeyColumnNames, "s", "t");
            string joinCondition = insertIfNotExists ? matchJoinCondition : "1=2";

            HashSet<int> matchedIds = autoMapOutput && update
                ? GetMatchedInternalIds(targetTableName, matchJoinCondition)
                : [];

            rowsUpdated[entityType] = 0;
            if (columnsToUpdate.Count > 0)
            {
                string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"{Context.DelimitIdentifier(c)}={Context.DelimitMemberAccess("s", c)}"));
                string updateSql = $"UPDATE {targetTableName} AS t SET {updateSetExpression} FROM {StagingTableName} AS s WHERE {joinCondition}";
                rowsUpdated[entityType] = Context.Database.ExecuteSqlInternal(updateSql, Options.CommandTimeout);
            }

            string insertColumnsSql = string.Join(",", columnsToInsert.Select(Context.DelimitIdentifier));
            string sourceColumnsSql = string.Join(",", columnsToInsert.Select(c => Context.DelimitMemberAccess("s", c)));
            string internalIdDelimited = Context.DelimitIdentifier(Constants.InternalId_ColumnName);

            // For auto-identity inserts (no keepIdentity, single auto-generated PK, pure insert),
            // capture the current max PK so we can correlate inserted rows back to staging rows via ROW_NUMBER.
            bool useRownumCorrelation = !keepIdentity && !insertIfNotExists && autoMapOutput
                && autoGeneratedColumns.Any() && GetGeneratedPrimaryKeyProperty() != null && PrimaryKeyColumnNames.Length == 1;
            long prevMaxId = useRownumCorrelation ? GetSqliteMaxId(targetTableName, Context.DelimitIdentifier(PrimaryKeyColumnNames[0])) : 0;

            // DELETE runs before INSERT so that newly inserted rows (with auto-generated PKs not present in staging)
            // are never accidentally removed by the NOT EXISTS delete condition.
            rowsDeleted[entityType] = 0;
            if (TableMapping.EntityType == entityType && delete)
            {
                // Use the merge condition for delete when one is defined (e.g. BulkSync on ExternalId),
                // otherwise fall back to PK-based delete.
                string deleteJoinCondition = mergeOnCondition != null ? matchJoinCondition : pkJoinCondition;
                string deleteSql = $"DELETE FROM {targetTableName} AS t WHERE NOT EXISTS (SELECT 1 FROM {StagingTableName} AS s WHERE {deleteJoinCondition})";
                rowsDeleted[entityType] = Context.Database.ExecuteSqlInternal(deleteSql, Options.CommandTimeout);
                for (int i = 0; i < rowsDeleted[entityType]; i++)
                    outputRows.Add(new BulkMergeOutputRow<T>(SqlMergeAction.Delete));
            }

            // Insert in __internalId order so staging row position aligns with assigned auto-increment ID.
            string insertSql = useRownumCorrelation
                ? $"INSERT INTO {targetTableName} ({insertColumnsSql}) SELECT {sourceColumnsSql} FROM {StagingTableName} AS s WHERE NOT EXISTS (SELECT 1 FROM {targetTableName} AS t WHERE {joinCondition}) ORDER BY s.{internalIdDelimited}"
                : $"INSERT INTO {targetTableName} ({insertColumnsSql}) SELECT {sourceColumnsSql} FROM {StagingTableName} AS s WHERE NOT EXISTS (SELECT 1 FROM {targetTableName} AS t WHERE {joinCondition})";
            rowsInserted[entityType] = Context.Database.ExecuteSqlInternal(insertSql, Options.CommandTimeout);
            if (keepIdentity && rowsInserted[entityType] > 0)
                SyncSqliteIdentitySequence(entityType);

            if (autoMapOutput)
            {
                string outputQuery;
                if (useRownumCorrelation && rowsInserted[entityType] > 0)
                {
                    // Entities had default PK values — staging.PK=0 can't join to target.PK=1..N.
                    // Use ROW_NUMBER: rows were inserted in __internalId order, assigned sequential IDs from prevMaxId+1.
                    string pkColDelimited = Context.DelimitIdentifier(PrimaryKeyColumnNames[0]);
                    string autoColsInTarget = string.Join(",", autoGeneratedColumns.Select(c => Context.DelimitIdentifier(c)));
                    string autoColsResult = string.Join(",", autoGeneratedColumns.Select(c => $"t.{Context.DelimitIdentifier(c)}"));
                    outputQuery = $"WITH s_ranked AS (SELECT {internalIdDelimited}, ROW_NUMBER() OVER (ORDER BY {internalIdDelimited}) AS rn FROM {StagingTableName}), t_ranked AS (SELECT {autoColsInTarget}, ROW_NUMBER() OVER (ORDER BY {pkColDelimited}) AS rn FROM {targetTableName} WHERE {pkColDelimited} > {prevMaxId}) SELECT s.{internalIdDelimited},{autoColsResult} FROM s_ranked s JOIN t_ranked t ON s.rn = t.rn";
                }
                else
                {
                    string outputColumnsSql = autoGeneratedColumns.Any()
                        ? "," + string.Join(",", autoGeneratedColumns.Select(c => Context.DelimitMemberAccess("t", c)))
                        : string.Empty;
                    outputQuery = $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)}{outputColumnsSql} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {matchJoinCondition}";
                }
                var bulkQueryResult = Context.BulkQuery(outputQuery, Options);
                var autoGeneratedColumnList = autoGeneratedColumns.ToList();
                foreach (var result in bulkQueryResult.Results)
                {
                    int entityId = Convert.ToInt32(result[0]);
                    bool wasMatched = matchedIds.Contains(entityId);
                    string action = wasMatched ? SqlMergeAction.Update : SqlMergeAction.Insert;
                    outputRows.Add(new BulkMergeOutputRow<T>(action));

                    if (entityMap.TryGetValue(entityId, out var entity) && allProperties.Count > 0)
                    {
                        var generatedProperties = allProperties.Where(p => autoGeneratedColumnList.Contains(p.GetColumnName())).ToList();
                        object[] entityValues = generatedProperties
                            .Select(p => TableMapping.GetValueFromProvider(p)(result[1 + autoGeneratedColumnList.IndexOf(p.GetColumnName())]))
                            .ToArray();
                        Context.SetStoreGeneratedValues(entity, generatedProperties, entityValues);
                    }
                }
            }
        }

        return new BulkMergeResult<T>
        {
            Output = outputRows,
            RowsAffected = rowsInserted.Values.LastOrDefault() + rowsUpdated.Values.LastOrDefault() + rowsDeleted.Values.LastOrDefault(),
            RowsDeleted = rowsDeleted.Values.LastOrDefault(),
            RowsInserted = rowsInserted.Values.LastOrDefault(),
            RowsUpdated = rowsUpdated.Values.LastOrDefault()
        };
    }
    private int ExecuteUpdateSqlite(Expression<Func<T, T, bool>> updateOnCondition)
    {
        int rowsUpdated = 0;
        foreach (var entityType in TableMapping.EntityTypes)
        {
            IEnumerable<string> columnsToUpdate = GetColumnNames(entityType);
            string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"{Context.DelimitIdentifier(c)}={Context.DelimitMemberAccess("s", c)}"));
            string targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            string updateSql = $"UPDATE {targetTableName} AS t SET {updateSetExpression} FROM {StagingTableName} AS s WHERE {CommonUtil<T>.GetJoinConditionSql(Context, updateOnCondition, PrimaryKeyColumnNames, "s", "t")}";
            rowsUpdated = Context.Database.ExecuteSqlInternal(updateSql, Options.CommandTimeout);
        }
        return rowsUpdated;
    }
    private HashSet<int> GetMatchedInternalIds(string targetTableName, string joinCondition)
    {
        var results = Context.BulkQuery(
            $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {joinCondition}",
            Options);
        return results.Results.Select(r => Convert.ToInt32(r[0])).ToHashSet();
    }
    private IProperty GetGeneratedPrimaryKeyProperty()
    {
        return TableMapping.EntityType.GetProperties().SingleOrDefault(o => o.IsPrimaryKey() && o.ValueGenerated != ValueGenerated.Never);
    }
    private long GetSqliteMaxId(string tableName, string pkColumn)
    {
        using var command = Connection.CreateCommand();
        command.CommandText = $"SELECT COALESCE(MAX({pkColumn}), 0) FROM {tableName}";
        command.Transaction = Transaction;
        return Convert.ToInt64(command.ExecuteScalar());
    }
    private void SyncSqliteIdentitySequence(IEntityType entityType)
    {
        _ = entityType;
    }
    internal void ValidateBulkMerge(Expression<Func<T, T, bool>> mergeOnCondition)
    {
        if (PrimaryKeyColumnNames.Length == 0 && mergeOnCondition == null)
            throw new InvalidDataException("BulkMerge requires that the entity have a primary key or that Options.MergeOnCondition be set");
    }
    internal void ValidateBulkUpdate(Expression<Func<T, T, bool>> updateOnCondition)
    {
        if (PrimaryKeyColumnNames.Length == 0 && updateOnCondition == null)
            throw new InvalidDataException("BulkUpdate requires that the entity have a primary key or the Options.UpdateOnCondition must be set.");

    }
    internal IEnumerable<string> GetColumnNames(bool includePrimaryKeys = false)
    {
        return GetColumnNames(null, includePrimaryKeys);
    }
    internal IEnumerable<string> GetColumnNames(IEntityType entityType, bool includePrimaryKeys = false)
    {
        return CommonUtil.FilterColumns(TableMapping.GetColumnNames(entityType, includePrimaryKeys), PrimaryKeyColumnNames, InputColumns, IgnoreColumns);
    }
}

