using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using N.EntityFrameworkCore.Extensions.Common;
using N.EntityFrameworkCore.Extensions.Sql;
using N.EntityFrameworkCore.Extensions.Util;

namespace N.EntityFrameworkCore.Extensions;

internal sealed partial class BulkOperation<T>
{
    internal async Task<BulkInsertResult<T>> BulkInsertStagingDataAsync(IEnumerable<T> entities, bool keepIdentity = true, bool useInternalId = false, CancellationToken cancellationToken = default)
    {
        IEnumerable<string> columnsToInsert = GetColumnNames(keepIdentity);
        string internalIdColumn = useInternalId ? Common.Constants.InternalId_ColumnName : null;
        await Context.Database.CloneTableAsync(SchemaQualifiedTableNames, StagingTableName, TableMapping.GetQualifiedColumnNames(columnsToInsert), internalIdColumn, cancellationToken);
        StagingTableCreated = true;
        return await DbContextExtensionsAsync.BulkInsertAsync(entities, Options, TableMapping, Connection, Transaction, StagingTableName, columnsToInsert, useInternalId, cancellationToken);
    }

    internal async Task<BulkMergeResult<T>> ExecuteMergeAsync(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update = false, bool delete = false, bool preallocatedIds = false, CancellationToken cancellationToken = default)
    {
        if (Context.Database.IsSqliteProvider())
            return await ExecuteMergeSqliteAsync(entityMap, mergeOnCondition, autoMapOutput, keepIdentity, insertIfNotExists, update, delete, preallocatedIds, cancellationToken);

        Dictionary<IEntityType, int> rowsInserted = [];
        Dictionary<IEntityType, int> rowsUpdated = [];
        Dictionary<IEntityType, int> rowsDeleted = [];
        Dictionary<IEntityType, int> rowsAffected = [];
        List<BulkMergeOutputRow<T>> outputRows = [];

        foreach (var entityType in TableMapping.EntityTypes)
        {
            rowsInserted[entityType] = 0;
            rowsUpdated[entityType] = 0;
            rowsDeleted[entityType] = 0;
            rowsAffected[entityType] = 0;

            var columnsToInsert = GetColumnNames(entityType, keepIdentity);
            var columnsToUpdate = update ? GetColumnNames(entityType) : [];
            var autoGeneratedColumns = autoMapOutput ? TableMapping.GetAutoGeneratedColumns(entityType) : [];
            var columnsToOutput = autoMapOutput ? GetMergeOutputColumns(autoGeneratedColumns, delete) : [];
            var deleteEntityType = TableMapping.EntityType == entityType && delete ? delete : false;

            string mergeOnConditionSql = insertIfNotExists ? CommonUtil<T>.GetJoinConditionSql(mergeOnCondition, PrimaryKeyColumnNames, "t", "s") : "1=2";
            bool toggleIdentity = keepIdentity && TableMapping.HasIdentityColumn;
            var mergeStatement = SqlStatement.CreateMerge(StagingTableName, entityType.GetSchemaQualifiedTableName(),
                mergeOnConditionSql, columnsToInsert, columnsToUpdate, columnsToOutput, deleteEntityType, toggleIdentity);

            if (autoMapOutput)
            {
                List<IProperty> allProperties =
                [
                    .. TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAdd).ToArray(),
                        .. TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAddOrUpdate).ToArray()
                ];

                var bulkQueryResult = await Context.BulkQueryAsync(mergeStatement.Sql, Connection, Transaction, Options, cancellationToken);
                rowsAffected[entityType] = bulkQueryResult.RowsAffected;

                foreach (var result in bulkQueryResult.Results)
                {
                    string action = (string)result[0];
                    outputRows.Add(new BulkMergeOutputRow<T>(action));

                    if (action == SqlMergeAction.Delete)
                    {
                        rowsDeleted[entityType]++;
                    }
                    else
                    {
                        int entityId = (int)result[1];
                        var entity = entityMap[entityId];
                        if (action == SqlMergeAction.Insert)
                        {
                            rowsInserted[entityType]++;
                            if (allProperties.Count != 0)
                            {
                                var entityValues = GetMergeOutputValues(columnsToOutput, result, allProperties);
                                Context.SetStoreGeneratedValues(entity, allProperties, entityValues);
                            }
                        }
                        else if (action == SqlMergeAction.Update)
                        {
                            rowsUpdated[entityType]++;
                            if (allProperties.Count != 0)
                            {
                                var entityValues = GetMergeOutputValues(columnsToOutput, result, allProperties);
                                Context.SetStoreGeneratedValues(entity, allProperties, entityValues);
                            }
                        }
                    }
                }
            }
            else
            {
                rowsAffected[entityType] = await Context.Database.ExecuteSqlAsync(mergeStatement.Sql, Options.CommandTimeout, cancellationToken);
            }
        }
        return new BulkMergeResult<T>
        {
            Output = outputRows,
            RowsAffected = rowsAffected.Values.LastOrDefault(),
            RowsDeleted = rowsDeleted.Values.LastOrDefault(),
            RowsInserted = rowsInserted.Values.LastOrDefault(),
            RowsUpdated = rowsUpdated.Values.LastOrDefault()
        };
    }
    internal async Task<int> ExecuteUpdateAsync(IEnumerable<T> entities, Expression<Func<T, T, bool>> updateOnCondition, CancellationToken cancellationToken = default)
    {
        if (Context.Database.IsSqliteProvider())
            return await ExecuteUpdateSqliteAsync(updateOnCondition, cancellationToken);

        int rowsUpdated = 0;
        foreach (var entityType in TableMapping.EntityTypes)
        {
            IEnumerable<string> columnsToUpdate = CommonUtil.FormatColumns(GetColumnNames(entityType));
            string updateSetExpression = string.Join(",", columnsToUpdate.Select(o => $"t.{o}=s.{o}"));
            string updateSql = $"UPDATE t SET {updateSetExpression} FROM {StagingTableName} AS s JOIN {CommonUtil.FormatTableName(entityType.GetSchemaQualifiedTableName())} AS t ON {CommonUtil<T>.GetJoinConditionSql(updateOnCondition, PrimaryKeyColumnNames, "s", "t")}; SELECT @@RowCount;";
            rowsUpdated = await Context.Database.ExecuteSqlAsync(updateSql, Options.CommandTimeout, cancellationToken);
        }
        return rowsUpdated;
    }
    private async Task<BulkMergeResult<T>> ExecuteMergeSqliteAsync(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update, bool delete, bool preallocatedIds = false, CancellationToken cancellationToken = default)
    {
        Dictionary<IEntityType, int> rowsInserted = [];
        Dictionary<IEntityType, int> rowsUpdated = [];
        Dictionary<IEntityType, int> rowsDeleted = [];
        List<BulkMergeOutputRow<T>> outputRows = [];

        foreach (var entityType in TableMapping.EntityTypes)
        {
            var targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            var columnsToInsert = GetColumnNames(entityType, keepIdentity).ToList();
            var columnsToUpdate = update ? GetColumnNames(entityType).ToList() : [];
            var autoGeneratedColumns = autoMapOutput ? TableMapping.GetAutoGeneratedColumns(entityType).ToList() : [];
            var allProperties = autoMapOutput
                ? TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAdd).Concat(TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAddOrUpdate)).ToList()
                : [];

            string matchJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, mergeOnCondition, PrimaryKeyColumnNames, "s", "t");
            string pkJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, null, PrimaryKeyColumnNames, "s", "t");
            string joinCondition = insertIfNotExists ? matchJoinCondition : "1=2";

            HashSet<int> matchedIds = autoMapOutput && update
                ? await GetMatchedInternalIdsAsync(targetTableName, matchJoinCondition, cancellationToken)
                : [];

            rowsUpdated[entityType] = 0;
            if (columnsToUpdate.Count > 0)
            {
                string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"{Context.DelimitIdentifier(c)}={Context.DelimitMemberAccess("s", c)}"));
                string updateSql = $"UPDATE {targetTableName} AS t SET {updateSetExpression} FROM {StagingTableName} AS s WHERE {joinCondition}";
                rowsUpdated[entityType] = await Context.Database.ExecuteSqlAsync(updateSql, Options.CommandTimeout, cancellationToken);
            }

            string insertColumnsSql = string.Join(",", columnsToInsert.Select(Context.DelimitIdentifier));
            string sourceColumnsSql = string.Join(",", columnsToInsert.Select(c => Context.DelimitMemberAccess("s", c)));
            string internalIdDelimited = Context.DelimitIdentifier(Constants.InternalId_ColumnName);

            bool useRownumCorrelation = !keepIdentity && !insertIfNotExists && autoMapOutput
                && autoGeneratedColumns.Any() && GetGeneratedPrimaryKeyProperty() != null && PrimaryKeyColumnNames.Length == 1;
            long prevMaxId = useRownumCorrelation ? await GetSqliteMaxIdAsync(targetTableName, Context.DelimitIdentifier(PrimaryKeyColumnNames[0]), cancellationToken) : 0;

            // DELETE runs before INSERT so that newly inserted rows (with auto-generated PKs not present in staging)
            // are never accidentally removed by the NOT EXISTS delete condition.
            rowsDeleted[entityType] = 0;
            if (TableMapping.EntityType == entityType && delete)
            {
                string deleteJoinCondition = mergeOnCondition != null ? matchJoinCondition : pkJoinCondition;
                string deleteSql = $"DELETE FROM {targetTableName} AS t WHERE NOT EXISTS (SELECT 1 FROM {StagingTableName} AS s WHERE {deleteJoinCondition})";
                rowsDeleted[entityType] = await Context.Database.ExecuteSqlAsync(deleteSql, Options.CommandTimeout, cancellationToken);
                for (int i = 0; i < rowsDeleted[entityType]; i++)
                    outputRows.Add(new BulkMergeOutputRow<T>(SqlMergeAction.Delete));
            }

            string insertSql = useRownumCorrelation
                ? $"INSERT INTO {targetTableName} ({insertColumnsSql}) SELECT {sourceColumnsSql} FROM {StagingTableName} AS s WHERE NOT EXISTS (SELECT 1 FROM {targetTableName} AS t WHERE {joinCondition}) ORDER BY s.{internalIdDelimited}"
                : $"INSERT INTO {targetTableName} ({insertColumnsSql}) SELECT {sourceColumnsSql} FROM {StagingTableName} AS s WHERE NOT EXISTS (SELECT 1 FROM {targetTableName} AS t WHERE {joinCondition})";
            rowsInserted[entityType] = await Context.Database.ExecuteSqlAsync(insertSql, Options.CommandTimeout, cancellationToken);
            if (keepIdentity && rowsInserted[entityType] > 0)
                await SyncSqliteIdentitySequenceAsync(entityType, cancellationToken);

            if (autoMapOutput)
            {
                string outputQuery;
                if (useRownumCorrelation && rowsInserted[entityType] > 0)
                {
                    string pkColDelimited = Context.DelimitIdentifier(PrimaryKeyColumnNames[0]);
                    string autoColsInTarget = string.Join(",", autoGeneratedColumns.Select(c => Context.DelimitIdentifier(c)));
                    string autoColsResult = string.Join(",", autoGeneratedColumns.Select(c => $"t.{Context.DelimitIdentifier(c)}"));
                    outputQuery = $"WITH s_ranked AS (SELECT {internalIdDelimited}, ROW_NUMBER() OVER (ORDER BY {internalIdDelimited}) AS rn FROM {StagingTableName}), t_ranked AS (SELECT {autoColsInTarget}, ROW_NUMBER() OVER (ORDER BY {pkColDelimited}) AS rn FROM {targetTableName} WHERE {pkColDelimited} > {prevMaxId}) SELECT s.{internalIdDelimited},{autoColsResult} FROM s_ranked s JOIN t_ranked t ON s.rn = t.rn";
                }
                else
                {
                    string outputColumnsSql = autoGeneratedColumns.Any()
                        ? "," + string.Join(",", autoGeneratedColumns.Select(c => Context.DelimitMemberAccess("t", c)))
                        : string.Empty;
                    outputQuery = $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)}{outputColumnsSql} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {matchJoinCondition}";
                }
                var bulkQueryResult = await Context.BulkQueryAsync(outputQuery, Connection, Transaction, Options, cancellationToken);
                var autoGeneratedColumnList = autoGeneratedColumns.ToList();
                foreach (var result in bulkQueryResult.Results)
                {
                    int entityId = Convert.ToInt32(result[0]);
                    string action = matchedIds.Contains(entityId) ? SqlMergeAction.Update : SqlMergeAction.Insert;
                    outputRows.Add(new BulkMergeOutputRow<T>(action));

                    if (entityMap.TryGetValue(entityId, out var entity) && allProperties.Count > 0)
                    {
                        var generatedProperties = allProperties.Where(p => autoGeneratedColumnList.Contains(p.GetColumnName())).ToList();
                        object[] entityValues = generatedProperties
                            .Select(p => TableMapping.GetValueFromProvider(p)(result[1 + autoGeneratedColumnList.IndexOf(p.GetColumnName())]))
                            .ToArray();
                        Context.SetStoreGeneratedValues(entity, generatedProperties, entityValues);
                    }
                }
            }
        }

        return new BulkMergeResult<T>
        {
            Output = outputRows,
            RowsAffected = rowsInserted.Values.LastOrDefault() + rowsUpdated.Values.LastOrDefault() + rowsDeleted.Values.LastOrDefault(),
            RowsDeleted = rowsDeleted.Values.LastOrDefault(),
            RowsInserted = rowsInserted.Values.LastOrDefault(),
            RowsUpdated = rowsUpdated.Values.LastOrDefault()
        };
    }
    private async Task<int> ExecuteUpdateSqliteAsync(Expression<Func<T, T, bool>> updateOnCondition, CancellationToken cancellationToken)
    {
        int rowsUpdated = 0;
        foreach (var entityType in TableMapping.EntityTypes)
        {
            IEnumerable<string> columnsToUpdate = GetColumnNames(entityType);
            string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"{Context.DelimitIdentifier(c)}={Context.DelimitMemberAccess("s", c)}"));
            string targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            string updateSql = $"UPDATE {targetTableName} AS t SET {updateSetExpression} FROM {StagingTableName} AS s WHERE {CommonUtil<T>.GetJoinConditionSql(Context, updateOnCondition, PrimaryKeyColumnNames, "s", "t")}";
            rowsUpdated = await Context.Database.ExecuteSqlAsync(updateSql, Options.CommandTimeout, cancellationToken);
        }
        return rowsUpdated;
    }
    private async Task<HashSet<int>> GetMatchedInternalIdsAsync(string targetTableName, string joinCondition, CancellationToken cancellationToken)
    {
        var results = await Context.BulkQueryAsync(
            $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {joinCondition}",
            Connection, Transaction, Options, cancellationToken);
        return results.Results.Select(r => Convert.ToInt32(r[0])).ToHashSet();
    }
    internal async Task PreallocateIdentityValuesAsync(IEnumerable<T> entities, CancellationToken cancellationToken)
    {
        var identityProperty = GetGeneratedPrimaryKeyProperty();
        if (identityProperty?.PropertyInfo == null)
            return;

        var entityList = entities.ToList();
        if (entityList.Count == 0)
            return;

        string tableName = Context.DelimitIdentifier(TableMapping.EntityType.GetTableName(), TableMapping.EntityType.GetSchema() ?? Context.Database.GetDefaultSchema());
        string sequenceSql = $"SELECT nextval(pg_get_serial_sequence('{tableName}', '{identityProperty.GetColumnName()}')) FROM generate_series(1, {entityList.Count})";
        await using var command = Connection.CreateCommand();
        command.CommandText = sequenceSql;
        command.Transaction = Transaction;
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        foreach (var entity in entityList)
        {
            if (!await reader.ReadAsync(cancellationToken))
                throw new InvalidDataException("Failed to allocate PostgreSql identity values.");

            object sequenceValue = Convert.ChangeType(reader.GetValue(0), identityProperty.ClrType);
#pragma warning disable EF1001
            if (entity is InternalEntityEntry internalEntry)
                internalEntry.SetStoreGeneratedValue(identityProperty, sequenceValue);
#pragma warning restore EF1001
            else
                identityProperty.PropertyInfo.SetValue(entity, sequenceValue);
        }
    }
    private async Task<long> GetSqliteMaxIdAsync(string tableName, string pkColumn, CancellationToken cancellationToken)
    {
        using var command = Connection.CreateCommand();
        command.CommandText = $"SELECT COALESCE(MAX({pkColumn}), 0) FROM {tableName}";
        command.Transaction = Transaction;
        var result = await command.ExecuteScalarAsync(cancellationToken);
        return Convert.ToInt64(result);
    }
    private Task SyncSqliteIdentitySequenceAsync(IEntityType entityType, CancellationToken cancellationToken)
    {
        _ = entityType;
        _ = cancellationToken;
        return Task.CompletedTask;
    }
}

